import mod.ModConfig

// Fabric bootstrap. Wires the common module into Fabric's loader.
plugins {
    id("java-library")
    id("net.fabricmc.fabric-loom")
}

// Minecraft + loader versions come from pkl/mod.pkl via buildSrc (one source).
// Scala + Kotlin toolchain versions still live in gradle.properties.
val modConfig = ModConfig.load(rootDir.resolve("pkl/mod.pkl"))
val minecraftVersion: String    = modConfig.mcVersion
val fabricLoaderVersion: String = modConfig.fabricLoaderVersion
val scalaVersion: String        = providers.gradleProperty("scala_version").get()
val kotlinVersion: String       = providers.gradleProperty("kotlin_version").get()

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

loom {
    splitEnvironmentSourceSets()
    mods {
        register("modid") {
            sourceSet(sourceSets.main.get())
            sourceSet(sourceSets.getByName("client"))
        }
    }
}

val commonProject = project(":common")
val commonSourceSets = commonProject.extensions.getByType<SourceSetContainer>()

dependencies {
    minecraft("com.mojang:minecraft:$minecraftVersion")
    implementation("net.fabricmc:fabric-loader:$fabricLoaderVersion")
    implementation(commonProject)
    "clientImplementation"(commonSourceSets.getByName("client").output)

    // Ship the Scala 3 runtime inside the fabric jar (jar-in-jar). In dev it's
    // already on the runtime classpath transitively via common.
    include("org.scala-lang:scala3-library_3:$scalaVersion")

    // Same for the Kotlin runtime so the shipped jar is self-contained.
    include("org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion")
}

// fabric.mod.json + the mixin configs are generated by Pkl into build/generated.
// Copy them into this module's resources at build time instead of committing them.
val generated = rootProject.layout.buildDirectory.dir("generated")
tasks.named<ProcessResources>("processResources") {
    dependsOn(":generatePklConfigs")
    from(generated.map { it.dir("fabric") }) // fabric.mod.json
    from(generated.map { it.dir("common") }) // modid.mixins.json + modid.client.mixins.json
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.release = 25
}
